### ISSUE TITLE
Feature Request - Custom launch options

### ISSUE THREAD

**Issue by vtcifer** [elanthia-online/lich-5#279]
Currently, saving launch options for quick entry, you only have wizard/wrath.  For those running on non-windows environments, I'd be nice to have the ability to specify custom options.

**Comment by OSXLich-Doug** [comment]
I believe you can?  Look for the `--without-frontend` type options.  If you tell me a bit more about what you are looking for, I'll see if it's a gap.

**Comment by sproctor** [comment]
If I understand what you mean, this is the subject of PR #285.

**Comment by vtcifer** [comment]
I'll take a look, pull that into my local repo and give it a test.  Thanks for the heads up!

**Comment by vtcifer** [comment]
Finally got a chance to test this, and that looks almost certainly to be what I'd be looking for.  Since genie can now accept command line arguments for login, looks like we might be able to use lich to launch genie seamlessly.  I'll do some more testing later but looks super promising.  Thanks!

**Comment by vtcifer** [comment]
So testing PR #285 in windows, and I get odd behavior trying to integrate genie with this. 

If I fetch all the settings, launch genie manually using these commands, it connects succesfully to the game.

`Genie.exe G:DR C:<character> H:storm.dr.game.play.net  P:11024 K:<key>`

If I launch lich in detached mode with no FE, I can connect successfully with genie using: 

`Genie.exe G:DR C:<character> H:localhost P:<port>`

But if I try to have lich launch genie with the following custom details it fails.  

2023-02-10 06:42:29: info: using custom launch command: Genie.exe G:DRT C:<character> H:localhost P:%port% K:%key%
2023-02-10 06:42:29: info: using working directory for custom launch command: G:\My Drive\G4
2023-02-10 06:42:29: info: gamehost: dr.simutronics.net
2023-02-10 06:42:29: info: gameport: 11624
2023-02-10 06:42:29: info: game: STORM
2023-02-10 06:42:29: info: launcher_cmd: Genie.exe G:DRT C:<character> H:localhost P:50440 K:[scrubbed key]

Genie actually launches, but essentially looks like it loses the connection or never actually connects?

It almost looks like lich isn't actually listening for the incoming connection, or establishing the connection to the game.  I'll try to get a packet capture later to get more details under the hood of what's happening network wise.

I guess also, what's the actual flow for those?  I'd think it would be lich connects to game, but sends nothing, starts listening for the incoming FE connection, then launches the custom command.

**Comment by OSXLich-Doug** [comment]
That gameport looks suspicious.  11024, not sure where that 6 came from?

You can even see it in the success line earlier.

**Comment by sproctor** [comment]
Just an FYI, you need to make sure to pick Stormfront / Wrayth in the radio selection above, because that's how it decides which protocol to connect with and which port to use. It's not super obvious that that is still important when specifying a custom command. Stormfront / Wrayth should probably be the default because I think it's the protocol supported by the majority of third part clients.

**Comment by vtcifer** [comment]
> That gameport looks suspicious. 11024, not sure where that 6 came from? You can even see it in the success line earlier.

That's DR Test (vs Prime / Plat / TF)

**Comment by vtcifer** [comment]
> Just an FYI, you need to make sure to pick Stormfront / Wrayth in the radio selection above, because that's how it decides which protocol to connect with and which port to use. It's not super obvious that that is still important when specifying a custom command. Stormfront / Wrayth should probably be the default because I think it's the protocol supported by the majority of third part clients.

Yeah, STORM/Wrayth was selected, as you get a different port for non-xml connections even to the same game + instance.  

Long term, I think a third option might be good for genie users that defaults similar to wizard/wrayth, but it would require knowledge of the exe path, since that's not fetchable from registry like wizard/wrayth are.  I'm trying to dig into this to better understand but gtk is oof.jpg for me.

**Comment by sproctor** [comment]
You shouldn't need to look at the GTK part at all. You probably want to look somewhere around here: https://github.com/sproctor/lich-5/blob/enable_custom_commands/lich.rbw#L4691

From what you wrote, I think your command might be wrong. It should be something like `Genie.exe G:DR C:<character> H:localhost P:%port%`. I don't know Genie, the character thing looks specific to there, but the `%port%` part should be entered exactly like that. Lich will replace it with the proper port. It's not the same as the server port.

**Comment by vtcifer** [comment]
> From what you wrote, I think your command might be wrong. It should be something like `Genie.exe G:DR C:<character> H:localhost P:%port%`. I don't know Genie, the character thing looks specific to there, but the `%port%` part should be entered exactly like that. Lich will replace it with the proper port. It's not the same as the server port.

That (port part at least) is what I put. 

> 2023-02-10 06:42:29: info: using custom launch command: Genie.exe G:DRT C: H:localhost P:%port% K:%key%

My understanding of the custom commands there is it's more or less telling lich not to 'login' to the game (that is send the key) but relying on the FE to do so.  It matches the templates that Wizard / Wrayth use.

Genie needs the DR+T to know which profile to load (DR vs DRT vs DRF can be different profiles within the FE itself)

In this test, I was using test environment instead of prime, but everything else was the same.

**Comment by vtcifer** [comment]
Ah yeah, I cheated to get the command on my linux box.  I had the commmand set to be 
`bash -c "echo G:DRT C:<character> H:localhost P:%port% K:%key%"`.  That was the first tests I did. :-)

**Comment by sproctor** [comment]
The method I said should have the port and key replaced. It's weird. I don't have access to Windows currently to test it.

**Comment by vtcifer** [comment]
Adding some additional logging messages, and it appears lich never gets beyond this line.

https://github.com/elanthia-online/lich-5/blob/staging/lich.rbw#L4717

I've wrapped that line in additional logging like this, and this is where nothing else gets written to the code.

```ruby
          Lich.log("debug: launching now")
          system ("start #{launcher_cmd}")
          Lich.log("debug: launched")
```
```
2023-02-10 12:55:00: info: game: STORM
2023-02-10 12:55:00: info: launcher_cmd: Genie.exe G:DR C:<scrubbed char> H:localhost P:57919 K:[scrubbed key]
2023-02-10 12:55:00: debug: launching now
```
Genie DOES launch, but it's almost like the ruby executable gets replaced by the genie one.  Same behavior if I use Wrayth with just the defaults too btw,..

```
2023-02-10 13:00:09: info: Lich 5.6.2
2023-02-10 13:00:09: info: Ruby 3.2.1
2023-02-10 13:00:09: info: x64-mingw-ucrt
2023-02-10 13:00:10: info: no force-mode info given
2023-02-10 13:00:57: info: Working against a Windows Platform for FE Executable
2023-02-10 13:00:57: info: Working against a Windows Platform for FE Location
2023-02-10 13:00:57: info: Current Windows working directory is C:\Program Files (x86)\SIMU\Wrayth
2023-02-10 13:00:57: info: gamehost: dr.simutronics.net
2023-02-10 13:00:57: info: gameport: 11024
2023-02-10 13:00:57: info: game: STORM
2023-02-10 13:00:57: info: launcher_cmd: Wrayth.exe /GDR/Hlocalhost/P58168/K[scrubbed key]
2023-02-10 13:00:57: debug: launching now
```

Also, it looks like when saving custom commands, on windows at least, the custom working directory doesn't get saved when using fully qualified (dive + path).

**Comment by ondreian** [comment]
this should almost certainly be using Open3, otherwise it will block the
ruby process:
https://stackoverflow.com/questions/6338908/ruby-difference-between-exec-system-and-x-or-backticks#18623297

**Comment by vtcifer** [comment]
Following that SO link, and checking out the flowchart someone used, it almost feels like we'd rather use fork()?  Do we really care what output the spawned process generates? 

Digging further, about using fork on windows w.ruby, and https://stackoverflow.com/questions/5998130/using-fork-in-windows-with-ruby indicates spawn is implemented for windows, and testing it, it seems to work, including getting custom command to launch, connect, and fully authenticate to the game.

> Just an FYI, you need to make sure to pick Stormfront / Wrayth in the radio selection above, because that's how it decides which protocol to connect with and which port to use. It's not super obvious that that is still important when specifying a custom command. Stormfront / Wrayth should probably be the default because I think it's the protocol supported by the majority of third part clients.

Getting back to this point we may want to let people know those radio buttons (WIZARD and STORMFRONT|WRAYTH) are more what 'protocol' do you want to use, or even just assume WRAYTH like you said going forward, and only allow users to select wizard under some "advanced options, only touch if you know what you're doing" checkbox.

**Comment by sproctor** [comment]
I don't know if genie cares which directory is launched from. You can try putting the path in the command line `c:\program files\genie\genie.exe ...`. My goal was to get things working with Warlock which doesn't care at all about the working directory. https://github.com/sproctor/warlock3

I'll look into the directory issue tomorrow if i have time.

**Comment by vtcifer** [comment]
> I don't know if genie cares which directory is launched from. You can try putting the path in the command line `c:\program files\genie\genie.exe ...`. My goal was to get things working with Warlock which doesn't care at all about the working directory. https://github.com/sproctor/warlock3
> 
> I'll look into the directory issue tomorrow if i have time.

I actually just found it, now that I had spawn working, and will submit a separate PR for it.

**Comment by sproctor** [comment]
The custom dir works fine on Linux. What was the issue?

**Comment by vtcifer** [comment]
> The custom dir works fine on Linux. What was the issue?

The details are in #292, but given how it manifests, I suspect it wasn't really saving the custom command directory, and was relying on linux referencing $PATH.

**Comment by sproctor** [comment]
No, the bug only is only in the path where you don't save the entry. I only tested with saving the entry.

**Comment by vtcifer** [comment]
That's not the right scope.  That's where it reads the _prior saved_ custom_launch_dir.

If you already had your account info setup from prior to move to lich5, this would not impact you.  It only occurs when setting up new accounts/characters from within lich5.

**Comment by OSXLich-Doug** [comment]
Merged the PR associated with issue.
