### ISSUE TITLE
Tabbed GUI layout doesn't show instance (at least test vs prime)

### ISSUE THREAD

**Issue by vtcifer** [elanthia-online/lich-5#280]
When using tabbed layout on gui, the instance (test vs prime) doesn't show up properly:

Non tabbed:
![image](https://user-images.githubusercontent.com/12104547/213213556-49542bb4-ef8f-43ca-96ba-5dd6613f3d99.png)

Tabbed: 
![image](https://user-images.githubusercontent.com/12104547/213213592-33edeb9e-b9de-40d1-8a3e-dde800dc25c3.png)

**Comment by OSXLich-Doug** [comment]
Thank you.  I'll see if I can address this in a future release.

**Comment by mrhoribu** [comment]
Resolved via #293
