### ISSUE TITLE
Some commandline arguments no longer work due to freezing of their values in [lib/constants.rb]

### ISSUE THREAD

**Issue by vtcifer** [elanthia-online/lich-5#304]
There are command line options to use custom directories for most (?all?) directories.
https://github.com/elanthia-online/lich-5/blob/40d87670b4a159c4b3e65c0151f83b09d58e39b7/lich.rbw#L4186-L4199

Due to the order these command line arguments are processed compared to the execution of lib/constants.rb, which freezes most of those cannot be set.
https://github.com/elanthia-online/lich-5/blob/40d87670b4a159c4b3e65c0151f83b09d58e39b7/lib/constants.rb#L2-L8

I'm not sure if the correct fix here is reordering the require of that constants.rb, or simply not freezing those.

**Comment by vtcifer** [comment]
Launch commandline:
```
./lich.rbw \
  --logs=/logs              \
  --temp=/debug             \
  --fallen                  \
  --without-frontend        \
  --genie                   \
  --detachable-client=8000  \
  --login <Character>
```

debug log output:
```
2023-02-23 07:39:30: info: Lich 5.6.2
2023-02-23 07:39:30: info: Ruby 3.2.1
2023-02-23 07:39:30: info: aarch64-linux
2023-02-23 07:39:30: info: DISPLAY environment variable is not set; not trying gtk
./lich.rbw:4197: warning: already initialized constant LOG_DIR
/usr/src/app/lib/constants.rb:7: warning: previous definition of LOG_DIR was here
./lich.rbw:4191: warning: already initialized constant TEMP_DIR
/usr/src/app/lib/constants.rb:2: warning: previous definition of TEMP_DIR was here
2023-02-23 07:39:30: info: using quick game entry settings for Venous
[snip]
```

**Comment by OSXLich-Doug** [comment]
Still works, though, doesn't it?  Those are warnings, not errors - I never can keep 'em all straight.

**Comment by vtcifer** [comment]
It doesn't.  LOG_DIR and TEMP_DIR remain at their frozen values, so those CLI arguments don't do anything.
