### ISSUE TITLE
infomon library - add infomon library and convert supporting modules

### ISSUE THREAD

**Issue by mrhoribu** [elanthia-online/lich-5#335]
# Create and test new `infomon` library module

Infomon.lic script should be integrated into core Lich. In order to do so, need to create a new infomon library for set/get/initialization of data as well as a parser to watch for various strings.

## New infomon supporting libraries needed
* [x] - infomon/cli.rb
* [x] - infomon/infomon.rb
* [x] - infomon/parser.rb
* [x] - activespells.rb
* [ ] - `GLD` (replace with filename / loc)
* [ ] - `STOW / READY / SHEATH` (replace with filename / loc)
* [x] - character/group.rb - new library, manage group
* [x] - character/disk.rb - new library, manage disk
* [ ] - `CHE | MHO` membership tracking

## Update existing library modules
Update eConvert existing module/classes to utilize new infomon system.
* [x] - armor.rb - existing library, update to use new Infomon code
* [x] - cman - existing library, update to use new Infomon code
* [x] - feat.rb - existing library, update to use new Infomon code
* [x] - shield.rb - existing library, update to use new Infomon code
* [x] - weapon.rb - existing library, update to use new Infomon code

## Breakout code from existing location into new library modules
* [x] - skills.rb - breakout of `lich.rbw` into new module, update to use new Infomon code
* [x] - spells.rb - existing library, update to use new Infomon code
* [x] - stats.rb - breakout of `lich.rbw` into new module, update to use new Infomon code

## New library modules tracking new data
* [x] - experience.rb - new library, use new Infomon code
* [x] - status.rb - new library, use new Infomon code

**Comment by mrhoribu** [comment]
Currently referencing #325  #334 #333 #331 #330 #328 #327 #326 #318

**Comment by OSXLich-Doug** [comment]
#318 Closed without merge - superseded by #325

**Comment by mrhoribu** [comment]
Believe the experience.rb is resolved with #334

**Comment by OSXLich-Doug** [comment]
#333 (activespells) completed.

**Comment by OSXLich-Doug** [comment]
#336 (skills) pushed for review
#337 (spells) pushed for review

**Comment by OSXLich-Doug** [comment]
#339 (CLI) pushed for review

**Comment by OSXLich-Doug** [comment]
#341 (psms) pushed for review

**Comment by OSXLich-Doug** [comment]
Looks to be complete with mostly green boards.  Look forward to any feedback.

**Comment by OSXLich-Doug** [comment]
And. . . added some requests.

**Comment by OSXLich-Doug** [comment]
Closing with three low-priority outstanding items - GLD, CHE / MHO and STOW / GIRD
