### ISSUE TITLE
Feat: Allow strings, symbols, integers indifferent query to Effects module

### ISSUE THREAD

**Issue by OSXLich-Doug** [elanthia-online/lich-5#41]
Category: User / Script Author convenience

    Feat: Indifferent method to determine results from Effects module
      Impacts: lich.rbw, some existing and many future scripts.  Closes defects in poorly designed .available? methods in PSM category modules (CMan, Shield, Weapon)
      Approach: Create utility module with methods to determine request variable class (Integer, String, Symbol) and appropriately query Effects module.  Potentially create flat hash that holds mappings of ID to NAME to use as basis for normalization.
      To-do: PR for existing prototype
      Needs: testing / feedback
      Currently working: Doug
      Status:
        09/19/2021 - prototype created

**Comment by OSXLich-Doug** [comment]
FYI - the feature updates are contained in the various PSM breakout.rb files (cman.rb, etc.)

@ondreian - Question: The semver will be updated in those files, but there will be no change to the lich.rbw file semver anticipated.  Is this accurate, or should a lib file semver change also be reflected in a lich.rbw semver change?

**Comment by ondreian** [comment]
there should only be 1 semver, the main one in lich.rb

**Comment by OSXLich-Doug** [comment]
Gotcha.  Thanks!
