### ISSUE TITLE
GS4 Voln Society Favor

### ISSUE THREAD

**Issue by mrhoribu** [elanthia-online/lich-5#441]
Track Voln Favor via `Society` module. Perhaps `Society.favor`. Should be able to always true up the value when seeing it from RESOURCE output:
```
Health: 232/232     Mana: 288/377     Stamina: 122/122     Spirit: 8/10
Voln Favor: 137,433
Essence: 46,923/50,000 (Weekly)     137,084/200,000 (Total)
Suffused Essence: 900
```
Would need to make sure to set back to nil/0 or whatever when society changes. Also unsure if favor gets set back to 0 on rank step-up.

The other option is perhaps to create a `Voln` module with appropriate parser to see usage of symbols and adjust automatically favor. Basically, baking into Lich5 the script `;sexual-favors`

**Comment by gs4-Xanlin** [comment]
favor does not get set to 0 on rank step-up.
