### ISSUE TITLE
Feat:  Permit GUI legacy view (list)

### ISSUE THREAD

**Issue by OSXLich-Doug** [elanthia-online/lich-5#46]
Category: Existing Lich Login (GUI) presentation

    Feat: Permit GUI legacy view (list) or GUI updated view (tabs) as user selection
      Impacts: lich.rbw
      Approach: add slider selection to permit user to choose
      To-do: Method to save selection (target lich.db3)
      Needs: prototype for review
      Currently working: Doug
      Status:
        09/19/2021 - proposed / not prioritized

**Comment by ondreian** [comment]
I don't think we should do this, this makes even more gtk code for you or someone to maintain
