### ISSUE TITLE
Protocol and Frontend are often conflated

### ISSUE THREAD

**Issue by sproctor** [elanthia-online/lich-5#510]
When viewing the saved entries, the protocol is listed, not the frontend.

Account entry requires picking between "Stormfront|Wrayth" and "Wizard". This radio select is also used for custom launcher. In the first instance, it's used to pick the frontend, in the second it's used to pick the protocol (or endpoints used for connecting).

I would suggest this should be a 3 options radio select "Wrayth", "Wizard", "Custom", and in "custom" the protocol could be selected. The ideal would be to maintain a list of mutable frontends with their protocol as a parameter.

The discovery of host/port is a complete mess because frontend isn't mapped to protocol and so each frontend needs to be handled for each game (and its variants). In my option, for frontends instead of conflicting flags, it should be something like: --game=(gs|gsplat|shattered|dr|drplat|fallen|drtest) --frontend=(stormfront|wizard|avalon|genie|etc). Each frontend should map to a protocol, and there should be a matrix of protocol/game both host and port. Sorry, minor rant there.

This isn't my project, but looking at the argument handling is tough to read. Instead of the ad hoc parsing, have you considered moving to something like https://docs.ruby-lang.org/en/3.2/OptionParser.html ?

**Comment by MahtraDR** [comment]
This topic comes up every once in a while and we all agree it could be cleaner. The main drag is not a lot of people use it on the command line, so there is minimal traction in this space. The various front ends don't even all work with both games, and lich really is GS heavy. The DR stuff happens in downstream scripts for the most part. If you want to create a branch and propose a change I'd be happy to test with you, as I also use Linux and command line arguments.

**Comment by sproctor** [comment]
I guess someone needs to make the call whether to improve this stuff or remove it. It looks like a maintenance nightmare. It's really hard to know where to start contributing here, because the technical debt looks overwhelming. I'm an IntelliJ suite user, and lich.rbw is too big for RubyMine (IntelliJ-based IDE) to do type inference.

I did a bit of investigation into updating the GTK bindings. I don't know how much is intentionally exposed to scripts. I know after being away for a few months, some scripts are now broken. Sorry, rambling again. Thanks for the good work. It's just really hard to contribute back in its current state. It's really cool that the data and scripts directories are now in the gitignore. I guess someone will eventually figure out the lib directory.
