### ISSUE TITLE
Chore: Naming convention and formatting standardization - core scripts

### ISSUE THREAD

**Issue by OSXLich-Doug** [elanthia-online/lich-5#64]
Clean up naming conventions and formatting in the following scripts:

* [ ] alias
* [ ] autostart
* [ ] go2
* [ ] infomon
* [ ] lich5-update
* [ ] lnet
* [ ] log
* [ ] repository
* [ ] vars
* [ ] version
* [ ] xnarost

Zero functional change expected to above.

In addition consider - retire narost and shim to xnarost; retire repository and shim to jinx.  May require jinx usability modifications for maximum adoption.

**Comment by jymamon** [comment]
For the formatting standardization part of this and the other tasks mentioning that, standardize to what?  If you have rubocop i mind, I've been doing that (and some other refactoring) over in my fork.  I'd be happy to PR the cleanup to here.

Fair warning, getting to standardized is a lot of churn and I'm only through the Layout/* rules.  Next on my list is any of the Style/* rules I can get for "free" with --autocorrect (safe versions only).  The other rules will come as time permits.

I was also planning to setup automatic running of rubocop on my fork to keep my future checkins clean. I haven't played around with github's workflows yet so I expect some trial-and-error on that.

**Comment by OSXLich-Doug** [comment]
Rubocop is implemented on submissions - closing as not needed.  Any required changes will be worked in stream with improvements / enhancements.

With thanks to @jymamon !
