### ISSUE TITLE
CritRanks regex updates needed

### ISSUE THREAD

**Issue by OSXLich-Doug** [elanthia-online/lich-5#654]
17:28:51: Vines of vicious briars whip out from your ghezyte long bow, raking the ranger with its thorns.  The ranger looks slightly ill as the glistening emerald coating from each briar works itself under its skin.
17:28:51:    ... 35 points of damage!
17:28:51:    Right hand wrenched hard as opponent is thrown to the ground!

      :type: GRAPPLE
      :location: RIGHT_HAND
      :rank: 7
      :damage: 35
      :position: PRONE
      :fatal: false
      :stunned: 5
      :amputated: false
      :crippled: false
      :sleeping: false
      :dazed: false
      :limb_favored: false
      :roundtime: 0
      :silenced: false
      :slowed: false
      :wound_rank: 1
      :secondary_wound:
      :regex: !ruby/regexp /The .*?'s right hand is wrenched hard as she is thrown to the ground./

Results: Location and damage match.  Regexp match failed.  Might be unique messaging to Briar flare.  Update regex to cover messages.

propose:  `:regex: !ruby/regexp /(?:The .*?'s r|R)ight hand is wrenched hard as (?:he|she|it|opponent) is thrown to the ground./`

**Comment by snperry85** [comment]
Have a few more examples for you. Good news is they seem to be confined to rank 7.

```
Vines of vicious briars whip out from your ghezyte long bow, raking the warden with its thorns.  The warden looks slightly ill as the glistening emerald coating from each briar works itself under its skin.
   ... 35 points of damage!
   Right leg wrenched hard as opponent is thrown to the ground!
   It is knocked to the ground!
```

```
Vines of vicious briars whip out from your ghezyte long bow, raking the fanatic with its thorns.  The fanatic looks slightly ill as the glistening emerald coating from each briar works itself under its skin.
   ... 35 points of damage!
   Left leg wrenched hard as opponent is thrown to the ground!
   It is knocked to the ground!
```

```
Vines of vicious briars whip out from your ghezyte long bow, raking the assassin with its thorns.  The assassin looks slightly ill as the glistening emerald coating from each briar works itself under its skin.
   ... 35 points of damage!
   The triton assassin thrown down hard, cracking her hip!
   /.*? takes a hard fall from being, cracking .*? hip./
```

```
Vines of vicious briars whip out from your ghezyte long bow, raking the fanatic with its thorns.  The fanatic looks slightly ill as the glistening emerald coating from each briar works itself under its skin.
   ... 35 points of damage!
   Head cracked as you throw the triton fanatic to the ground!
   /.*?'s head is cracked as (?:it|she|he) is thrown to the ground./
```

**Comment by snperry85** [comment]
On disruption, Back   Rank 9, there's an extra s there.
`:regex           => /Spine ripped from .*?s's body and thrown to the ground./ } },`

On grapple table, Head  Rank 9, need 2 spaces between sentences.
`:regex           => /Head crushed! Resulting death is... messy./`


On some of the non-corporeal regex's there are multiple sentences. The first sentence is omitted from the regex on a few of them. I didn't find any overlap between them and the other tables. Maybe they were skipped on purpose or accidentally. The one that's right/left I understand of course.
```
Non-Corporeal
Head
Rank 9
  Strong attack separates head from shoulders. Head disappears in the breeze as a new one forms on the [target]'s shoulders!
Neck
Rank 2
  Flashy attack passes through the side of the neck. Ethereal fluids spray forth and quickly vanish into vapor!
Rank 5
  Strong attack rips through the neck! To your horror, the [target]'s substance flows around the wound without leaving a trace!
Rank 8
  Brutal blow to the neck sends head flying! The head floats up and settles back in place as easily as a hat. What is this, a haberdashery?
Rank 9
  Tremendous strike! Vapor rushes from the neck following the blow!
Right Arm
Rank 5
  Good hit! Right shoulder is ripped from its socket, then wriggles back into place.
Left Arm
Rank 5
  Good hit! Left shoulder is ripped from its socket, then wriggles back into place.
```
The reason I bring this up is it presents a problem when parsing in real time. Granted the solution in my specific scenario is an easy one. Not asking for them to be changed, just bringing it up in case it in unintentional. 
My use case is tracking flare damage. We know they're structed as Flare message -> damage -> crit message. And so it is easy to recognize that I need to continue for the actual crit match.
```
when Regex.union(DAMAGE_FLARES.values)
  flare = DAMAGE_FLARES.find { |_,regex| line =~ regex }&.first
  
  # next line should be damage
  damage_line = get
  if damage_line =~ /\.\.\. (\d+) points? of damage!/
    damage = $1.to_i
  
    # next line should be crit
    crit_line = get
    # some of the crits have two lines and the first line doesn't match with critranks. So need to push to the next line.
    crit_line = get if crit_line =~ SKIP_THIS_CRIT_LINE
    crit = CritRanks.parse(crit_line).values.first || {} 
```

**Comment by snperry85** [comment]
Non-corporeal  Rank 4  left leg  ... animal companion ...
I get these may not be able to be incorporated. I haven't pursued if any of the 3rd party messaging includes **the** vs **your** but I recognize the obstacle that presents.
```
   A bearded woodland panther charges forward and slashes her claws at an ethereal triton psionicist faster than she can react!
   ... 20 points of damage!
   A fine strike immobilizes the left leg for an instant.
   The triton psionicist looks miffed.

   /A fine strike pins the left leg for an instant./
```
Non-corporeal Rank 5 head 
```
 A bearded woodland panther charges forward and slashes her claws at a spectral triton protector faster than she can react!
    ... 25 points of damage!
    The triton protector's head wavers as the attack passes right through it!
    /.*?'s head wavers as your attack passes right through it./
```
Non-corporeal Rank 3 neck
```
 A bearded woodland panther charges forward and slashes her claws at an ethereal triton psionicist faster than she can react!
    ... 15 points of damage!
    Smoky tendrils rise from the triton psionicist's neck as the attack sweeps through.
    /Smoky tendrils rise from neck as your attack sweeps through./
```
Slash Rank 2 back
```
 A bearded woodland panther charges forward and slashes her claws at a triton warden faster than he can react!
    ... 10 points of damage!
    Feint to the left as the triton warden dodges that way!
    Deep gouges left in back.
  /Feint to the left goes astray as .*? dodges./  
```

**Comment by OSXLich-Doug** [comment]
Closing issue.
