### ISSUE TITLE
Allow custom scripts to be stored in a subdirectory

### ISSUE THREAD

**Issue by BinuDR** [elanthia-online/lich-5#95]
Hey Gemstone peeps!  I was adding this feature to the Dragonrealms version of lich and happened to check Matt's github and saw this request there too.  https://github.com/matt-lowe/Lich/issues/23

I just submitted a PR for this change in our repo.  Here's a link to it if you want to add it to your latest lich version too.

Basically it allows you to have a `lich/scripts/custom` directory and can run scripts from there.

https://github.com/dragon-realms/dr-lich/pull/64

**Comment by OSXLich-Doug** [comment]
Thanks, @BinuDR - this will be incorporated, sometime this week if plans come about!
